# fly.toml app configuration file generated for dsaa-schd on 2023-12-22T23:33:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dsaa-schd"
primary_region = "ewr"

[build]

[[mounts]]
  source = "data"
  destination = "/pb/pb_data"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 8093
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
