version: "3"

services:
  pocketbase:
    build: .
    ports:
      - 8093:8093
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_migrations:/pb/pb_migrations
      # - ./pb_hooks:/pb/pb_hooks
    environment:
      - VIRTUAL_HOST=pb.*
      - VIRTUAL_PORT=8093
